// src/components/seo.tsx
import { useEffect } from 'react'

type SeoProps = {
  title?: string
  description?: string
  path?: string
  image?: string
  type?: 'website' | 'article'
  jsonLd?: Record<string, unknown>
}

const siteUrl = 'https://whoisclebs.com'
const defaultTitle = 'whoisclebs.com — Engenharia de software sem teatro'
const defaultDescription = 'Blog e portfolio de Clebson A. Fonseca sobre engenharia de software, arquitetura, pagamentos, frontend e operação.'
const defaultImage = '/profile/clebson.png'

function upsertMeta(selector: string, attributes: Record<string, string>) {
  let element = document.head.querySelector(selector) as HTMLMetaElement | HTMLLinkElement | null

  if (!element) {
    element = selector.startsWith('link') ? document.createElement('link') : document.createElement('meta')
    document.head.appendChild(element)
  }

  for (const [key, value] of Object.entries(attributes)) {
    element.setAttribute(key, value)
  }
}

export function SEO({ title, description, path = '/', image = defaultImage, type = 'website', jsonLd }: SeoProps) {
  useEffect(() => {
    const resolvedTitle = title ? `${title} — whoisclebs.com` : defaultTitle
    const resolvedDescription = description ?? defaultDescription
    const canonical = `${siteUrl}${path}`
    const imageUrl = image.startsWith('http') ? image : `${siteUrl}${image}`

    document.title = resolvedTitle
    upsertMeta('meta[name="description"]', { name: 'description', content: resolvedDescription })
    upsertMeta('link[rel="canonical"]', { rel: 'canonical', href: canonical })
    upsertMeta('meta[property="og:title"]', { property: 'og:title', content: resolvedTitle })
    upsertMeta('meta[property="og:description"]', { property: 'og:description', content: resolvedDescription })
    upsertMeta('meta[property="og:type"]', { property: 'og:type', content: type })
    upsertMeta('meta[property="og:url"]', { property: 'og:url', content: canonical })
    upsertMeta('meta[property="og:image"]', { property: 'og:image', content: imageUrl })
    upsertMeta('meta[name="twitter:card"]', { name: 'twitter:card', content: 'summary_large_image' })
    upsertMeta('meta[name="twitter:title"]', { name: 'twitter:title', content: resolvedTitle })
    upsertMeta('meta[name="twitter:description"]', { name: 'twitter:description', content: resolvedDescription })
    upsertMeta('meta[name="twitter:image"]', { name: 'twitter:image', content: imageUrl })

    let script = document.head.querySelector('#jsonld') as HTMLScriptElement | null
    if (!script) {
      script = document.createElement('script')
      script.id = 'jsonld'
      script.type = 'application/ld+json'
      document.head.appendChild(script)
    }
    script.textContent = JSON.stringify(jsonLd ?? {
      '@context': 'https://schema.org',
      '@type': 'Person',
      name: 'Clebson A. Fonseca',
      url: siteUrl,
      image: `${siteUrl}/profile/clebson.png`,
      sameAs: ['https://github.com/whoisclebs', 'https://linkedin.com/in/whoisclebs'],
      jobTitle: 'Software Engineer',
    })
  }, [description, image, jsonLd, path, title, type])

  return null
}

// src/lib/components/Seo.svelte
<script lang="ts">
  import { absoluteUrl } from '$lib/routing/paths'
  import { DEFAULT_IMAGE, type Seo } from '$lib/seo'

  let { seo }: { seo: Seo } = $props()

  const canonical = $derived(absoluteUrl(seo.path))
  const image = $derived(absoluteUrl(seo.image ?? DEFAULT_IMAGE))
  const alternates = $derived(Object.entries(seo.alternates ?? {}).filter((entry): entry is [string, string] => Boolean(entry[1])))
  const ptAlternate = $derived(alternates.find(([locale]) => locale === 'pt-BR')?.[1])
  // JSON do próprio conteúdo; `<` escapado para não fechar a tag. Montado aqui para o template ficar simples.
  const jsonLdTag = $derived(
    seo.jsonLd
      ? `<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@graph': Array.isArray(seo.jsonLd) ? seo.jsonLd : [seo.jsonLd] }).replaceAll('<', '\\u003c')}</` + 'script>'
      : undefined,
  )
</script>

<svelte:head>
  <title>{seo.title}</title>
  <meta name="description" content={seo.description} />
  <link rel="canonical" href={canonical} />
  {#if alternates.length > 1}
    {#each alternates as [locale, path] (locale)}
      <link rel="alternate" hreflang={locale} href={absoluteUrl(path)} />
    {/each}
    {#if ptAlternate}
      <link rel="alternate" hreflang="x-default" href={absoluteUrl(ptAlternate)} />
    {/if}
  {/if}
  <meta property="og:site_name" content="whoisclebs.com" />
  <meta property="og:locale" content={seo.locale === 'en' ? 'en_US' : 'pt_BR'} />
  <meta property="og:title" content={seo.title} />
  <meta property="og:description" content={seo.description} />
  <meta property="og:type" content={seo.type ?? 'website'} />
  <meta property="og:url" content={canonical} />
  <meta property="og:image" content={image} />
  {#if seo.publishedTime}
    <meta property="article:published_time" content={seo.publishedTime} />
  {/if}
  {#if seo.modifiedTime}
    <meta property="article:modified_time" content={seo.modifiedTime} />
  {/if}
  <meta name="twitter:card" content="summary_large_image" />
  {#if jsonLdTag}
    <!-- eslint-disable-next-line svelte/no-at-html-tags -- JSON-LD serializado do próprio conteúdo, com < escapado -->
    {@html jsonLdTag}
  {/if}
</svelte:head>
